[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tamilPY"
version = "0.1.7"
description = "TamilPY Framework — schema-driven Python web framework"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Selvaganapathi Arumugam" }
]
dependencies = [
    "typer",
    "jinja2",
    "rich",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pydantic",
    "pymongo",
    "psycopg2-binary",
    "pymysql",
    "PyJWT",
    "passlib[bcrypt]",
    "bcrypt<4.1",
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
[project.scripts]
tpy = "tpy.cli:app"

[tool.setuptools.packages.find]
include = ["tpy*"]

[tool.setuptools.package-data]
tpy = ["templates/**/*"]
